#!/bin/bash

sudo add-apt-repository ppa:nginx/stable -y
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo mkdir /var/www/demoapp
sudo chown -R ubuntu:ubuntu /var/www/demoapp/
cd /var/www/demoapp/
sudo apt-get install python-virtualenv -y
sudo chown -R $USER:$USER /var/www/demoapp/
virtualenv venv
. venv/bin/activate
pip install flask
sudo ufw allow 8081
sudo cp ~/SoftEngProj1/hello.py ./
sudo apt-get install build-essential python python-dev -y
pip install uwsgi
sudo rm /etc/nginx/sites-enabled/default
sudo cp ~/SoftEngProj1/demoapp_nginx.conf ./
sudo ln -s /var/www/demoapp/demoapp_nginx.conf
sudo ln -s /var/www/demoapp/demoapp_nginx.conf /etc/nginx/conf.d/
sudo /etc/init.d/nginx restart
sudo cp ~/SoftEngProj1/demoapp_uwsgi.ini ./
sudo mkdir -p /var/log/uwsgi
sudo chown -R ubuntu:ubuntu /var/log/uwsgi
sudo chown -R $USER:$USER /var/log/uwsgi
